- name: ensuring directories for {{ name }}
  file: path={{ item }} state=directory
  with_items: app_dirs

- name: installing config for {{ name }}
  template: src=app.ini.j2 dest={{ supervisor_home }}/conf.d/{{ name }}.ini
  register: supervisor_app_config

- name: starting {{ name }}
  supervisorctl: name={{ name }} state=present {{ super_args }}

- name: updating configuration for {{ name }}
  shell: '{{ supervisorctl_path }} -c {{ supervisor_config }} reread; {{ supervisorctl_path }} -c {{ supervisor_config }} update {{ name }};'
  when: supervisor_app_config|changed
